name: "Sitecite"
description: "Check if citation is still available"
inputs:
  textfield:
    description: "Key in JSON to take quote from"
    required: true
    default: "quote"
  urlfield:
    description: "Key in JSON to fetching from"
    required: true
    default: "url"
  path:
    description: "Path to config file"
    required: true
    default: "./sitecite"
outputs:
  report:
    description: "Sitecite result"
runs:
  using: "node12"
  main: "dist/index.js"
