name: "Sitecite"
description: "Check if citation is still available"
inputs:
  path:
    description: "Path to config file"
    required: true
    default: "./sitecite"
outputs:
  report:
    description: "Sitecite result"
runs:
  using: "node12"
  main: "dist/index.js"
