name: "Sitecite"
description: "Check if citation is still available"
inputs:
  token:
    description: "Github token"
    required: true
  textfield:
    description: "Key in JSON to take quote from"
    required: true
    default: "quote"
  urlfield:
    description: "Key in JSON to fetching from"
    required: true
    default: "url"
  path:
    description: "Path to config file"
    required: true
    default: "./sitecite.json"
  failOnNotFound:
    description: "Make check fail when citation is not found"
    required: false
    default: false
outputs:
  failures:
    description: "Has sitecite ran into failures?"
  results:
    description: "Sitecite result"
runs:
  using: "node12"
  main: "dist/index.min.js"
